export const UPDATE_FILES = "UPDATE_FILES";
export const UPDATE_CURRENT_PATH = "UPDATE_CURRENT_PATH";
export const UPDATE_CURRENT_IMAGE = "UPDATE_CURRENT_IMAGE";
export const UPDATE_HISTORY = "UPDATE_HISTORY";